# Banco Local
default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  username: root
  password: 
  database: crypto_wallet
  host: 127.0.0.1
  port: 3306

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default